services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: esgipwd
      POSTGRES_DB: esgi
      POSTGRES_USER: esgi
    ports:
      - "5432:5432"
    volumes:
      - ./docker-compose/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-compose/db/ready.sql:/docker-entrypoint-initdb.d/ready.sql
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
